export const personalInfo = {
  name: "Snehal Yelle",
  firstName: "Snehal",
  lastName: "Yelle",
  title: "Brand Content Strategist | Copy Supervisor | Content Marketing Manager",
  shortTitle: "Brand Content Strategist",
  location: "Mumbai, India",
  email: "snehal.yelle45@gmail.com",
  phone: "7977780285",
  linkedin: "linkedin.com/in/snehal-yelle-99007613b",
  linkedinUrl: "https://www.linkedin.com/in/snehal-yelle-99007613b",
  yearsExperience: 7,
  brandsCount: 10,
  awardsCount: 3,
  bio: "Forward-thinking strategist specializing in entertainment marketing, social-first storytelling, and integrated campaign strategy. I build campaigns that audiences remember and brands measure — blending big creative ideas with performance insights.",
  heroBio: "7+ years crafting award-winning 360° campaigns for OTT, television & film — Sony LIV, Zee TV, Dharma Productions and more.",
};

export const experience = [
  {
    company: "The Small Big Idea",
    role: "Strategist, Brand Content Marketing",
    years: "2021 – Present",
    isCurrent: true,
    color: "#D4537E",
    pillBg: "#FDF0F5",
    pillColor: "#993556",
    borderColor: "#D4537E",
  },
  {
    company: "Koffeetech Communications",
    role: "Sr. Executive, Content Marketing",
    years: "2019 – 2021",
    isCurrent: false,
    color: "#7F77DD",
    pillBg: "#EEEDFE",
    pillColor: "#3C3489",
    borderColor: "#7F77DD",
  },
  {
    company: "AdEngage",
    role: "Copywriter",
    years: "2018",
    isCurrent: false,
    color: "#1D9E75",
    pillBg: "#E1F5EE",
    pillColor: "#085041",
    borderColor: "#1D9E75",
  },
  {
    company: "Mazeweb Technologies",
    role: "Digital Marketing Executive",
    years: "2016 – 2017",
    isCurrent: false,
    color: "#EF9F27",
    pillBg: "#FAEEDA",
    pillColor: "#633806",
    borderColor: "#EF9F27",
  },
];

export const campaigns = [
  {
    id: 1,
    title: "Kesari 2",
    subtitle: "Social Media Plan",
    brand: "Film · Dharma Productions",
    result: "Platform-specific digital storytelling strategy",
    summary: "Built a social-first launch approach designed to turn anticipation into sustained conversation across platforms.",
    highlight: "Launch Architecture",
    bgColor: "#FDF0F5",
    textColor: "#993556",
    large: true,
    label: "Kesari 2 · Social Campaign",
    image: "",
  },
  {
    id: 2,
    title: "Shark Tank India",
    subtitle: "Social Media Strategy",
    brand: "Sony LIV",
    result: "Content planning & launch strategy",
    summary: "Mapped content buckets and launch beats to keep the show culturally relevant beyond episodic drops.",
    highlight: "Momentum Building",
    bgColor: "#EEEDFE",
    textColor: "#3C3489",
    large: false,
    label: "Shark Tank India",
    image: "",
  },
  {
    id: 3,
    title: "Baalveer x Ganji Chudail",
    subtitle: "Creative Crossover Campaign",
    brand: "Sony LIV",
    result: "Cross-IP storytelling & audience expansion",
    summary: "Turned a crossover moment into a campaign hook that widened audience interest and boosted narrative intrigue.",
    highlight: "Audience Expansion",
    bgColor: "#E1F5EE",
    textColor: "#085041",
    large: false,
    label: "Baalveer x Ganji Chudail",
    image: "",
  },
  {
    id: 4,
    title: "Sa Re Ga Ma Pa Li'l Champs",
    subtitle: "Li'l Champs Challenge",
    brand: "Zee TV",
    result: "UGC challenge driving show engagement",
    summary: "Designed a participation-led social mechanic that encouraged audience interaction around the show format.",
    highlight: "UGC Activation",
    bgColor: "#FAEEDA",
    textColor: "#633806",
    large: false,
    label: "Sa Re Ga Ma Pa Li'l Champs",
    image: "",
  },
  {
    id: 5,
    title: "DID SuperMoms",
    subtitle: "#SuperMomsKaSuperStep",
    brand: "&TV",
    result: "Viral hashtag campaign & audience participation",
    summary: "Built a social challenge format around celebration and shareability to increase campaign visibility organically.",
    highlight: "Participation Spike",
    bgColor: "#E6F1FB",
    textColor: "#0C447C",
    large: false,
    label: "DID SuperMoms",
    image: "",
  },
];

export const skills = [
  { name: "Content Strategy", bg: "#FDF0F5", border: "#F4C0D1", color: "#993556" },
  { name: "Campaign Ideation", bg: "#EEEDFE", border: "#CECBF6", color: "#3C3489" },
  { name: "Social Media Marketing", bg: "#E1F5EE", border: "#9FE1CB", color: "#085041" },
  { name: "Influencer Marketing", bg: "#FAEEDA", border: "#FAC775", color: "#633806" },
  { name: "Brand Management", bg: "#E6F1FB", border: "#B5D4F4", color: "#0C447C" },
  { name: "Copywriting", bg: "#FDF0F5", border: "#F4C0D1", color: "#993556" },
  { name: "Digital Marketing", bg: "#EEEDFE", border: "#CECBF6", color: "#3C3489" },
  { name: "Content Calendar", bg: "#E1F5EE", border: "#9FE1CB", color: "#085041" },
  { name: "Market Research", bg: "#FAEEDA", border: "#FAC775", color: "#633806" },
  { name: "Team Leadership", bg: "#E6F1FB", border: "#B5D4F4", color: "#0C447C" },
  { name: "360° Campaigns", bg: "#FDF0F5", border: "#F4C0D1", color: "#993556" },
  { name: "OTT Platform Marketing", bg: "#EEEDFE", border: "#CECBF6", color: "#3C3489" },
  { name: "Project Management", bg: "#E1F5EE", border: "#9FE1CB", color: "#085041" },
  { name: "Client Servicing", bg: "#FAEEDA", border: "#FAC775", color: "#633806" },
  { name: "Account Management", bg: "#E6F1FB", border: "#B5D4F4", color: "#0C447C" },
  { name: "Brief Interpretation", bg: "#FDF0F5", border: "#F4C0D1", color: "#993556" },
  { name: "Consumer Insights", bg: "#EEEDFE", border: "#CECBF6", color: "#3C3489" },
  { name: "Competitive Analysis", bg: "#E1F5EE", border: "#9FE1CB", color: "#085041" },
  { name: "Creative Direction", bg: "#FAEEDA", border: "#FAC775", color: "#633806" },
  { name: "Presentation Design", bg: "#E6F1FB", border: "#B5D4F4", color: "#0C447C" },
  { name: "Stakeholder Alignment", bg: "#FDF0F5", border: "#F4C0D1", color: "#993556" },
  { name: "Content Tone Development", bg: "#EEEDFE", border: "#CECBF6", color: "#3C3489" },
  { name: "Reporting & Analytics", bg: "#E1F5EE", border: "#9FE1CB", color: "#085041" },
  { name: "Cross-Functional Coordination", bg: "#FAEEDA", border: "#FAC775", color: "#633806" },
  { name: "Campaign Reporting", bg: "#E6F1FB", border: "#B5D4F4", color: "#0C447C" },
  { name: "Brand Positioning", bg: "#FDF0F5", border: "#F4C0D1", color: "#993556" },
  { name: "Launch Planning", bg: "#EEEDFE", border: "#CECBF6", color: "#3C3489" },
  { name: "Content Systems", bg: "#E1F5EE", border: "#9FE1CB", color: "#085041" },
];

export const awards = [
  {
    name: "Best Digital Campaign",
    showYear: "MOBEXX 2023",
    show: "DID Li'l Masters",
  },
  {
    name: "Best Marketing Campaign",
    showYear: "ET Trendies 2023",
    show: "DID SuperMoms",
  },
  {
    name: "Experimental OOH Media",
    showYear: "Prime Time Awards 2022",
    show: "Gadar 2",
  },
];

export const brands = [
  { name: "Sony LIV", bg: "#FDF0F5", border: "#F4C0D1", color: "#993556" },
  { name: "Zee TV", bg: "#EEEDFE", border: "#CECBF6", color: "#3C3489" },
  { name: "Dharma", bg: "#E1F5EE", border: "#9FE1CB", color: "#085041" },
  { name: "&TV", bg: "#FDF0F5", border: "#F4C0D1", color: "#993556" },
  { name: "Zee Cinema", bg: "#EEEDFE", border: "#CECBF6", color: "#3C3489" },
  { name: "Zing", bg: "#E1F5EE", border: "#9FE1CB", color: "#085041" },
  { name: "Abundantia", bg: "#FFFBF0", border: "#FAC775", color: "#633806" },
  { name: "Pooja Films", bg: "#F1EFE8", border: "#D3D1C7", color: "#444441" },
  { name: "ZEE5", bg: "#FDF0F5", border: "#F4C0D1", color: "#993556" },
];

export const navLinks = [
  { label: "Home", href: "#home" },
  { label: "About", href: "#about" },
  { label: "Work", href: "#campaigns" },
  { label: "Awards", href: "#awards" },
  { label: "Contact", href: "#contact" },
];
